version: '3.8'

x-dev:
    &proxy_conf
    http_proxy: "${HTTP_PROXY}"
    https_proxy: "${HTTPS_PROXY}"
    
services:
    cli:
        container_name: go_scripts
        # image: golang:bullseye
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - './:/app'
        restart: always
        command: tail -f /dev/null
        working_dir: '/app'
        environment:
            << : *proxy_conf

    